---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn install
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - yarn install
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --release-channel $EXP_RELEASE_CHANNEL
